node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('Build') {
	 nodejs(nodeJSInstallationName: 'nodejs') {
	   sh 'rm -rf node_modules'
	   sh 'rm package-lock.json yarn.lock'
	   sh 'npm cache clear --force'
       sh 'npm install'
     }
   }
   stage('Test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm run ci'
     }
   }
}
